apiVersion: batch/v1
kind: Job
metadata:
  name: update-oauth-client-secret
  namespace: auth
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:15
        env:
        - name: PGHOST
          value: "auth-dev-pg.ck94qmk8ufd3.us-east-1.rds.amazonaws.com"
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: "appdb"
        - name: PGUSER
          value: "appuser"
        - name: PGPASSWORD
          value: "O1L6h>e1FT9LQr2e}aqq"
        command:
        - /bin/sh
        - -c
        - |
          psql << 'EOF'
          -- Eliminar el cliente existente
          DELETE FROM oauth_clients WHERE client_id = 'auth-to-connectivity-client';
          
          -- Crear nuevo cliente con secret simple
          INSERT INTO oauth_clients (
              id,
              client_id,
              client_secret,
              name,
              description,
              active,
              created_at,
              updated_at
          ) VALUES (
              gen_random_uuid(),
              'auth-connectivity',
              '$2a$10$YourHashedPasswordHere',
              'Auth to Connectivity Client',
              'OAuth2 client for auth-service to communicate with connectivity-service',
              true,
              NOW(),
              NOW()
          );
          
          SELECT client_id, name, active FROM oauth_clients WHERE client_id = 'auth-connectivity';
          EOF
      restartPolicy: Never
  backoffLimit: 3
