apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: auth-sa
      initContainers: []
      containers:
        - name: auth-service
          imagePullPolicy: Always
