global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'auth-microservice'
    replica: 'prometheus'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Auth Service metrics
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
        labels:
          service: 'auth-service'
          env: 'development'
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          env: 'development'

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          env: 'development'

