apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: auth-service
    count: 3

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml
  - path: ingress.yaml

images:
  - name: ghcr.io/kristianrpo/auth-microservice
    newTag: v1.0.0

