basePath: /api/v1
definitions:
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.LogoutRequest:
    properties:
      refresh_token:
        type: string
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.RegisterRequest:
    properties:
      email:
        type: string
      name:
        minLength: 2
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse:
    properties:
      code:
        type: string
      details:
        type: string
      error:
        type: string
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.HealthResponse:
    properties:
      services:
        additionalProperties:
          type: string
        type: object
      status:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.MessageResponse:
    properties:
      message:
        type: string
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
  github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: kristianrpo@example.com
    name: Kristian Rodriguez
    url: https://github.com/kristianrpo
  description: |-
    Authentication and user management service with JWT.
    This microservice provides endpoints for user registration, login, token refresh, and user management.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Auth Microservice API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful, tokens generated
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.TokenResponse'
        "400":
          description: Invalid request or missing data
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
      summary: User login
      tags:
      - Authentication
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Invalidates user tokens (access and refresh)
      parameters:
      - description: Refresh token (optional)
        in: body
        name: request
        schema:
          $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Logout successful
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.MessageResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: User logout
      tags:
      - Authentication
  /auth/me:
    get:
      consumes:
      - application/json
      description: Get the authenticated user's information using the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: User information
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.UserResponse'
        "401":
          description: Unauthorized or invalid token
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - Authentication
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Generate a new token pair using a valid refresh token
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens refreshed successfully
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.TokenResponse'
        "400":
          description: Invalid request or missing data
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "401":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
      summary: Refresh tokens
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account in the system
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.UserResponse'
        "400":
          description: Invalid request or missing data
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
      summary: Register a new user
      tags:
      - Authentication
  /health:
    get:
      consumes:
      - application/json
      description: Check the health status of the service and its dependencies (database,
        Redis)
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.HealthResponse'
        "503":
          description: Service is unhealthy
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.HealthResponse'
      summary: Complete health check
      tags:
      - Health
  /health/live:
    get:
      consumes:
      - application/json
      description: Check if the service is alive (used by Kubernetes)
      produces:
      - application/json
      responses:
        "200":
          description: Service is alive
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Liveness check
      tags:
      - Health
  /health/ready:
    get:
      consumes:
      - application/json
      description: Check if the service is ready to receive traffic (used by Kubernetes)
      produces:
      - application/json
      responses:
        "200":
          description: Service is ready
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service is not ready
          schema:
            $ref: '#/definitions/github_com_kristianrpo_auth-microservice_internal_adapters_http_dto_response.ErrorResponse'
      summary: Readiness check
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Endpoints related to authentication and authorization
  name: Authentication
- description: Endpoints for checking the service status
  name: Health
