apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-external-secret
  labels:
    app: auth-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: auth-secrets
    creationPolicy: Owner
  data:
  - secretKey: db_host
    remoteRef:
      key: auth-microservice/database
      property: host
  - secretKey: db_port
    remoteRef:
      key: auth-microservice/database
      property: port
  - secretKey: db_user
    remoteRef:
      key: auth-microservice/database
      property: username
  - secretKey: db_password
    remoteRef:
      key: auth-microservice/database
      property: password
  - secretKey: db_name
    remoteRef:
      key: auth-microservice/database
      property: database
  - secretKey: db_ssl_mode
    remoteRef:
      key: auth-microservice/database
      property: ssl_mode
  - secretKey: redis_host
    remoteRef:
      key: auth-microservice/redis
      property: host
  - secretKey: redis_port
    remoteRef:
      key: auth-microservice/redis
      property: port
  - secretKey: redis_password
    remoteRef:
      key: auth-microservice/redis
      property: password
  - secretKey: redis_db
    remoteRef:
      key: auth-microservice/redis
      property: database
  - secretKey: jwt_secret
    remoteRef:
      key: auth-microservice/jwt
      property: secret

