apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: auth-service
  managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - external-secret.yaml
  - hpa.yaml
  - service-account.yaml
  - servicemonitor.yaml
  - poddisruptionbudget.yaml

images:
  - name: ghcr.io/kristianrpo/auth-microservice
    newTag: latest

