apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
  labels:
    app: auth-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/api/v1/metrics"
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http