name: Auth Microservice CI

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: |
          golangci-lint run --output.checkstyle.path=golangci-lint-report.xml || true
          golangci-lint run --output.text.path=stdout --output.text.colors=true

      - name: Upload Lint Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-reports
          path: golangci-lint-report.xml

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run Unit Tests with Coverage
        run: |
          # Run tests with verbose output
          echo "Running unit tests..."
          go test ./internal/.../tests/... -v 2>&1 | tee test-output.log
          
          # Extract test summary
          grep -E "(^=== RUN|^--- PASS|^--- FAIL|^PASS$|^FAIL$)" test-output.log | tail -40 > test-summary.txt
          
          # Generate coverage report (excluding test directories for accurate coverage)
          echo "Generating coverage report..."
          go test ./internal/.../tests -coverpkg=$(go list ./internal/... | grep -v '/tests' | tr '\n' ',' | sed 's/,$$//') -coverprofile=coverage.out -covermode=atomic
          
          # Generate coverage in multiple formats
          go tool cover -html=coverage.out -o coverage.html
          go tool cover -func=coverage.out -o coverage.txt
          
          # Display coverage summary
          echo "Coverage Summary:"
          go tool cover -func=coverage.out | tail -1

      - name: Upload Test Reports Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            coverage.out
            coverage.html
            coverage.txt
            test-output.log
            test-summary.txt

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/auth-microservice
          tags: |
            type=sha,prefix=main-
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download lint artifacts
        uses: actions/download-artifact@v4
        with:
          name: lint-reports
          path: .

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: .

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}